@php
    // $company = "Aptech Learning";    
    $company = "";    
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{{ route('home') }}">Home</a></li>
            <li><a href="{{ route('about') }}">About</a></li>
            <li><a href="{{ route('welcome') }}">Welcome</a></li>
        </ul>
    </nav>
    
    <h1>Welcome Home</h1>
    <h2>{{ "This string is generated by blade syntex" }}</h2>
    {!! "<h4>This heading tag is by blade</h4>" !!}
    {{-- this is not readable by blade --}}
    
    @if ($company)
    <h3>{{ $company }}</h3>
    @else
    <h3>{{ "No Company" }}</h3>
    @endif
    
</body>
</html>