@php
    $name = 'Maria Kasmani';
    $students = [
        ['name' => 'Maria Kasman', 'dob' => '17-Oct-2004'],
        ['name' => 'Husnain Ali', 'dob' => '20-Mar-1999'],
        ['name' => 'Muhammad Haqqani', 'dob' => '17-Aug-2005'],
        ['name' => 'Muhammad Shameel', 'dob' => '23-Jul-2006'],
        ['name' => 'Abdur Rehman', 'dob' => '09-Jun-2005'],
    ];
@endphp
<!DOCTYPE html>
<html lang="en">

    @include('head',['title' => 'Welcome to Home'])

<body>
    @include('navbar')
    {{ 'this text is generated by php' }}

    {!! "<p>$name</p>" !!}

    {{ 4 + (3 * 7) / 2 }}

    <br>

    @for ($i = 1; $i <= 10; $i++)
        @if ($i % 2 == 0)
            @continue
        @endif
        <p>{{ $i }}</p>
    @endfor

    @foreach ($students as $student)
        @if ($loop->first)
            <p style="color: green">
            @elseif($loop->last)
            <p style="color: red">
            @else
            <p>
        @endif
        {{ $loop->index }}. Dear {{ $student['name'] }}, you are
        {{ \Carbon\Carbon::parse($student['dob'])->age }}
        years old.- result {{ $loop->iteration }}/{{ $loop->count }}
        </p>
    @endforeach

</body>

</html>
